web:
  protected_access: false
  eshop_url: 'https://obchod.altar.cz/draci-doupe-a-jine-rpg-hry-draci-doupe-plus-c-1_7.html'
  menu:
    position_fixed: false
    home_button:
      show: true
  name: 'DrD+ kalkulátor pro boj'
  title_smiley: ''
  cookies_postfix: 'boj'
google:
  analytics_id: 'UA-121206931-18'

